excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - BookManager/AppResources/R/R.generated.swift
disabled_rules:
  - cyclomatic_complexity
  - colon
  - function_body_length
  - function_parameter_count
  - identifier_name
  - line_length
  - nesting
  - type_name
  - force_cast
